# Generated by Django 3.2 on 2021-06-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_auto_20210603_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_group_types', to='settings.group'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='lesson_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_lesson_patterns', to='settings.patterns'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_lessons', to='settings.lessontype'),
        ),
    ]
