# Generated by Django 3.2 on 2021-06-05 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_auto_20210604_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_subject_name', to='settings.subjects'),
        ),
    ]
