# Generated by Django 3.2 on 2021-06-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_salary_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='added_time',
            field=models.DateField(),
        ),
    ]
