# Generated by Django 3.2 on 2021-06-05 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_alter_building_added_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='lesson_pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_lesson_patterns', to='settings.patterns'),
        ),
        migrations.AlterField(
            model_name='other',
            name='subject_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_subject_name', to='settings.subjects'),
        ),
    ]
