# Generated by Django 3.2 on 2021-06-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_auto_20210606_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='id_mumber',
            new_name='id_code',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='reason',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='fired_date',
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(default='erkak', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='id_card_number',
            field=models.CharField(default='vrnvrtoinb', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='middle_name',
            field=models.CharField(default='vrrvrtbr', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='finish_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
