# Generated by Django 3.2.9 on 2021-11-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_auto_20210627_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouppattern',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newgroup',
            name='group_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='newgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacherrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
