# Generated by Django 3.2.9 on 2021-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_auto_20211110_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgroup',
            name='payment',
            field=models.CharField(max_length=30),
        ),
    ]
