# Generated by Django 3.2.9 on 2021-11-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_alter_newgroup_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgroup',
            name='total_lessons',
            field=models.CharField(max_length=30),
        ),
    ]
